import type { Metadata } from "next";
import Sidebar from './comp-1/sidebar/sidebar'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
    <body>
      <div className="app-container">
          <div className="main-container">
            {children}
          </div>
      </div>
    </body>
    </html>
  );
}
